version: '3.8'

services:
  website:
    build:
      context: ./website
    ports:
      - "5001:5001"
    depends_on:
      - mysql
      - server

  mysql:
    build:
      context: ./MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cloud
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

  server:
    build:
      context: ./Server
    ports:
      - "5000:5000"
    networks:
      default:
        aliases:
          - server

networks:
  default:
    driver: bridge