version: '3.8'

services:
  emailservice:
    image: cloud-resource-pooling/EmailService:latest
    container_name: emailservice
    ports:
      - "61000:61000"  # Adjust the ports if needed
    environment:
      - ENV_VAR=example_value
    networks:
      - app-network

  server:
    image: cloud-resource-pooling/Server:latest
    container_name: server
    ports:
      - "5000:5000"  # Adjust the ports if needed
    environment:
      - ENV_VAR=example_value
    depends_on:
      - emailservice
    networks:
      - app-network

  slave:
    image: cloud-resource-pooling/Slave:latest
    container_name: slave
    environment:
      - ENV_VAR=example_value
    depends_on:
      - server
    networks:
      - app-network

  website:
    image: cloud-resource-pooling/Website:latest
    container_name: website
    ports:
      - "5001:5000"  # Adjust the ports if needed
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
