apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: email
  name: email
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: email
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/p2p-default: "true"
        io.kompose.service: email
    spec:
      containers:
        - image: sit-distibuted-email
          imagePullPolicy: IfNotPresent
          name: email
          ports:
            - containerPort: 61000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}