apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/p2p-default: "true"
        io.kompose.service: server
    spec:
      containers:
        - image: sit-distibuted-server
          imagePullPolicy: IfNotPresent
          name: server
          ports:
            - containerPort: 5000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
