apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: website
  name: website
spec:
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
  selector:
    io.kompose.service: website
status:
  loadBalancer: {}
