apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: website
  name: website
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: website
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/p2p-default: "true"
        io.kompose.service: website
    spec:
      containers:
        - image: sit-distributed-website
          imagePullPolicy: IfNotPresent
          name: website
          ports:
            - containerPort: 5001
              hostPort: 5001
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
