apiVersion: v1
kind: Service
metadata:
  name: website
spec:
  type: NodePort
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
      nodePort: 30001
  selector:
    io.kompose.service: website
status:
  loadBalancer: {}
